spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate

logging:
  level:
    root: INFO
    org.springframework.web: INFO
  file:
    name: logs/app.log

  logback:
    rolling policy:
      max-file-size: 2MB
      max-history: 10
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %level %thread - %msg%n"